const players = [
  {
    icon: "./images/players/barbarian.jpg",
    avatar: "./images/players/barbarian.gif",
    name: "Doss",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    speed: 100,
    status: "alive",
    description: "High health - Low speed",
  },
  {
    icon: "./images/players/mage.jpg",
    avatar: "./images/players/mage.gif",
    name: "Waltz",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    speed: 100,
    status: "alive",
    description: "Kills or gets killed",
  },
  {
    icon: "./images/players/knight.jpg",
    avatar: "./images/players/knight.gif",
    name: "Polish",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    speed: 100,
    status: "alive",
    description: "High defence - Low damage",
  },
  {
    icon: "./images/players/dagger.jpg",
    avatar: "./images/players/dagger.gif",
    name: "Robbo",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    speed: 100,
    status: "alive",
    description: "High energy - Low damage",
  },
  {
    icon: "./images/players/alchemist.jpg",
    avatar: "./images/players/alchemist.gif",
    name: "Erika",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    speed: 100,
    status: "alive",
    description: "High energy - Low damage",
  },
];

const mobs = [
  {
    icon: "./images/mobs/drake.jpg",
    avatar: "./images/mobs/knight.gif",
    name: "Gurgaz",
    type: "enemy",
    health: 100,
    energy: 50,
    strength: 100,
    speed: 50,
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/skeletor1.gif",
    name: "Skeletor",
    type: "enemy",
    health: 100,
    energy: 50,
    strength: 100,
    strength: 60,
    speed: 90,
    status: "alive",
  },
  {
    icon: "./images/mobs/mordekaiser.jpg",
    avatar: "./images/mobs/unnamed.gif",
    name: "Mordekaiser",
    type: "enemy",
    health: 100,
    energy: 30,
    strength: 60,
    speed: 90,
    status: "alive",
  },
  {
    icon: "./images/mobs/drake.jpg",
    avatar: "./images/mobs/malphite.gif",
    name: "Poop",
    type: "enemy",
    health: 100,
    energy: 30,
    strength: 60,
    speed: 90,
    status: "alive",
  },
  // {
  //   icon: "./images/players/warewolf.jpg",
  //   avatar: "./images/players/warewolf.gif",
  //   name: "Warwick",
  //   classe: "warewolf",
  //   type: "player",
  //   health: 100,
  //   energy: 100,
  //   strength: 100,
  //   speed: 100,
  //   status: "alive",
  //   description: "High health regeneration - Low Stats",
  // },
  // {
  //   icon: "./images/players/ninja.jpg",
  //   avatar: "./images/players/ninja.gif",
  //   name: "Shen",
  //   classe: "ninja",
  //   type: "player",
  //   health: 100,
  //   energy: 100,
  //   strength: 100,
  //   speed: 100,
  //   status: "alive",
  //   description: "High Speed - Low Strength",
  // },
  // {
  //   icon: "./images/players/demon.jpg",
  //   avatar: "./images/players/demon.gif",
  //   name: "Oni",
  //   classe: "demon",
  //   type: "player",
  //   health: 100,
  //   energy: 100,
  //   strength: 100,
  //   speed: 100,
  //   status: "alive",
  //   description: "High Damage - Low Health",
  // },
];
