const sounds = [
  audioPunch,
  audioPunch1,
  audioPunch2,
  audioSword,
  audioSword1,
  audioSlap,
];

const players = [
  {
    icon: "./images/players/barbarian.jpg",
    avatar: "./images/players/barbarian.gif",
    name: "Doss",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    status: "alive",
    description: "High health - Low speed",
  },
  {
    icon: "./images/players/mage.jpg",
    avatar: "./images/players/mage.gif",
    name: "Waltz",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    status: "alive",
    description: "Kills or gets killed",
  },
  {
    icon: "./images/players/knight.jpg",
    avatar: "./images/players/knight.gif",
    name: "Polish",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    speed: 70,
    status: "alive",
    description: "High defence - Low damage",
  },
  {
    icon: "./images/players/dagger.jpg",
    avatar: "./images/players/dagger.gif",
    name: "Robbo",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    status: "alive",
    description: "High energy - Low damage",
  },
  {
    icon: "./images/players/alchemist.jpg",
    avatar: "./images/players/alchemist.gif",
    name: "Erika",
    classe: "human",
    type: "player",
    health: 100,
    energy: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    status: "alive",
    description: "High energy - Low damage",
  },
];

const mobs = [
  {
    icon: "./images/mobs/renekaj.jpg",
    avatar: "./images/mobs/renekaj.gif",
    name: "Renekaj",
    type: "enemy",
    energy: diceRoll(50, 100),
    health: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/skeletor.gif",
    name: "Skeletor",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/nidalkaj.jpg",
    avatar: "./images/mobs/nidalkaj.gif",
    name: "Nidalkaj",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/feticcio.jpg",
    avatar: "./images/mobs/feticcio.gif",
    name: "Feticcio",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/zedaj.jpg",
    avatar: "./images/mobs/zedaj.gif",
    name: "Zedaj",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/drake.gif",
    name: "Drake",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/malakaj.jpg",
    avatar: "./images/mobs/malakaj.gif",
    name: "Malakaj",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/hyena.gif",
    name: "Hyena",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/abraxas.gif",
    name: "Abraxas",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/knight.gif",
    name: "knight",
    type: "enemy",
    health: diceRoll(50, 100),
    energy: diceRoll(50, 100),
    strength: diceRoll(50, 100),
    defence: diceRoll(50, 100),
    speed: diceRoll(50, 100),
    status: "alive",
  },
];
