const players = [
  {
    icon: "./images/players/ww.jpg",
    avatar: "./images/players/wolf.gif",
    name: "Warwick",
    classe: "warewolf",
    type: "player",
    health: 100,
    energy: 50,
    strength: 100,
    speed: 50,
    status: "alive",
    description: "fast energy regeneration",
  },
  {
    icon: "./images/players/shen.jpg",
    avatar: "./images/players/ninja.gif",
    name: "Shen",
    classe: "ninja",
    type: "player",
    health: 60,
    energy: 70,
    strength: 120,
    speed: 100,
    status: "alive",
    description: "high dodge and initiative",
  },
];

const mobs = [
  {
    icon: "./images/mobs/gurgaz.jpg",
    avatar: "./images/mobs/goblin1.gif",
    name: "Gurgaz",
    classe: "goblin",
    type: "enemy",
    health: 100,
    energy: 50,
    strength: 100,
    speed: 50,
    status: "alive",
  },
  {
    icon: "./images/mobs/skeletor.jpg",
    avatar: "./images/mobs/monster.gif",
    name: "Skeletor",
    classe: "undead",
    type: "enemy",
    health: 100,
    health: 80,
    energy: 30,
    strength: 60,
    speed: 90,
    status: "alive",
  },
  ,
  {
    icon: "./images/mobs/mordekaiser.jpg",
    avatar: "./images/mobs/mordekaiser1.gif",
    name: "Mordekaiser",
    classe: "phantom",
    type: "enemy",
    health: 100,
    health: 80,
    energy: 30,
    strength: 60,
    speed: 90,
    status: "alive",
  },
];
